version: '3.8'
services:
  resume-analyzer:
    build: .
    container_name: resume-analyzer
    restart: always
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
